### ISSUE TITLE
Backslash for unicode breaks down often in recent version of lean4

### ISSUE THREAD

**Issue by Qiu233** [leanprover/vscode-lean4#489]
Sometimes the backslash symbol `\` become plain text rather with an underline indicating it's pending further input. To fix it I must either:

* restart vscode
* reopen the current file
* restart file (only works for my macbook, but not for wsl)

I have been experiencing this problem very often since updating to 4.9.0, on both macos and windows with wsl. The cause isn't clear. I tried different vscode extension versions published months ago but the problem still remains, so the language server is more likely to have caused this.

**Comment by Qiu233** [comment]
* no, I was using it from wsl and macos, from months ago, and this problem only occurs recently
* as I just tried now, yes, this problem still happens after switching to `v0.0.124`, also note that I didn't restart vscode after switching the extension version
* I guess no, my macos vscode has only environment for lean4
* YES there are errors in the developer tools, and they seem to have a common pattern. Here's the most recent ones:

> console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'dispose')
> C @ console.ts:137
> console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'dispose')
>     at t.AbbreviationRewriterFeature.<anonymous> (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:159973)
>     at Generator.next (<anonymous>)
>     at s (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:158285)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> C @ console.ts:137
> mainThreadExtensionService.ts:81 [leanprover.lean4]Cannot read properties of undefined (reading 'dispose')
> $onExtensionRuntimeError @ mainThreadExtensionService.ts:81
> mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'dispose')
>     at t.AbbreviationRewriterFeature.<anonymous> (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:159973)
>     at Generator.next (<anonymous>)
>     at s (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:158285)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> $onExtensionRuntimeError @ mainThreadExtensionService.ts:82
> console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'dispose')
> C @ console.ts:137
> console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'dispose')
>     at t.AbbreviationRewriterFeature.<anonymous> (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:159973)
>     at Generator.next (<anonymous>)
>     at s (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:158285)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> C @ console.ts:137
> mainThreadExtensionService.ts:81 [leanprover.lean4]Cannot read properties of undefined (reading 'dispose')
> $onExtensionRuntimeError @ mainThreadExtensionService.ts:81
> mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'dispose')
>     at t.AbbreviationRewriterFeature.<anonymous> (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:159973)
>     at Generator.next (<anonymous>)
>     at s (/home/qiu/.vscode-server/extensions/leanprover.lean4-0.0.170/dist/extension.js:1:158285)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by mhuisi** [comment]
> also note that I didn't restart vscode after switching the extension version

You should! Or at least click the "Restart Extensions" button that shows up in the extension entry after the update. Otherwise it will still use the previous version.

Could you also double-check that the issue indeed does not occur with Lean v4.8.0 on v0.0.170 of the extension?

**Comment by mhuisi** [comment]
(By the way, the error you saw above is unrelated but will be fixed by #492. Thanks for the report.)

**Comment by mhuisi** [comment]
Are you still encountering this issue?

**Comment by mhuisi** [comment]
> But sometimes unicode fails, leave it as is and the bottom panel of vscode shows up with errors. 

What is the error you are seeing and what is your current vscode-lean4 version?

FWIW, the fact that replacing the abbreviation sometimes fails is unfortunately something we can't fix (VS Code doesn't support transactions for updating editor state, so if the editor state has changed since the abbreviation mechanism was called, VS Code simply rejects our edits to the document). 

> There's another cursor issue which I am not sure related to this issue or not.

For this issue, it would also be good to know what your vscode-lean4 version is. We fixed this issue a while ago *unless* you are also using the Vim extension, in which case text edits issued by the Vim extension and vscode-lean4 can interfere.
