### ISSUE TITLE
Error: command 'lean4.input.convert' already exists

### ISSUE THREAD

**Issue by Ekwem2024** [leanprover/vscode-lean4#551]
Internal error (while activating Lean 4 extension): Error: command 'lean4.input.convert' already exists

Error: command 'lean4.input.convert' already exists
	at Y0.registerCommand (file:///c:/Users/emmau/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31527)
	at Object.registerTextEditorCommand (file:///c:/Users/emmau/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:36569)
	at new t.AbbreviationRewriterFeature (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:159060)
	at new t.AbbreviationFeature (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:157343)
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:198012
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:198234
	at Generator.next (<anonymous>)
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:195856
	at new Promise (<anonymous>)
	at s (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:195601)
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:196107
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:286099
	at Generator.next (<anonymous>)
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:285940
	at new Promise (<anonymous>)
	at i (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:285685)
	at t.displayInternalErrorsIn (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:286048)
	at c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:196071
	at Generator.next (<anonymous>)
	at s (c:\Users\emmau\.vscode\extensions\leanprover.lean4-0.0.185\dist\extension.js:1:195658)

**Comment by mhuisi** [comment]
Which other extensions do you have installed? (E.g. did you install the "Harmonic Lean 4" extension?)

**Comment by mhuisi** [comment]
Ah, yes, you really do not want to install all Lean 4 extensions since some of them are duplicates of the official ones and contribute the same VS Code commands, which VS Code does not allow. I'd uninstall all the other ones except for the Paperproof extension if you want to use it.
Does the issue still occur after uninstalling the other extensions?

**Comment by mhuisi** [comment]
Closing this issue for now since this was likely caused by installing redundant extensions.
